### ISSUE TITLE
Feature Request: Notify Followers on Ticket

### ISSUE THREAD

**Issue by ShawnSack** [jundis/CWSlack-SlashCommands#20]
Similar to what cwslack-follow is currently doing except instead of initiating the follow from Slack, I receive notifications if I "Follow" a ticket in CW. This I believe will require some way to map users in CW to users in Slack.

**Comment by cuchanski** [comment]
My understanding was that follow is for all users with that channel to keep everyone informed when a ticket is followed.

Mapping CW to Slack is just more effort and administration? Just curious - how would that help keep an eye on things?

**Comment by jundis** [comment]
@cuchanski cwslack-follow.php enables direct messages whenever a ticket is updated as long as you /follow <ticket number> that ticket. The general channel incoming is cwslack-incoming.php

@ShawnSack  is referring to the follow button below that appears at the top of each ticket, and I'm looking into being able to use this. You most likely would need to have all users Slack names be the same as their CW names to complete this, but I'm looking into it as an option for cwslack-incoming.php instead of using the file based /follow command. Both would be able to work independently still if you prefer /follow over the button.

![image](https://cloud.githubusercontent.com/assets/766768/18391029/27499dd0-7672-11e6-8874-c8233a5b24c4.png)

**Comment by jundis** [comment]
Unfortunately the followers of a ticket are not returned by any API call that I can find, so the /follow command is the only way to do this it seems.

Sorry!
