### ISSUE TITLE
Remove the requirement for middleware / web, investigate making this a plugin? Its too good!

### ISSUE THREAD

**Issue by cuchanski** [jundis/CWSlack-SlashCommands#21]
Saved us a streamline license / month we were using for notifications
Thank you!

**Comment by jundis** [comment]
I've investigated this quite extensively at this point, unfortunately there are a couple hurdles with it so I'm going to close this issue as will not fix.

Slack does not do any sort of plugin hosting for things submitted to the Slack app directory. All slash commands you can use through integrations like Giphy and Trello send to their respective company servers.

On the ConnectWise end, there's no way to develop a plugin that I can find that will accept Slack input.

Given these, the only solution would be for us to host a server to forward between Slack and ConnectWise for all companies. While I'm certain that is possible and wouldn't be too much of a hassle to setup for authentication and the like, I'm not certain enough in my programming ability to ensure security on that.

Also, in order to accept and forward these requests there would have to be some nominal fee for the service to cover hosting, and at that point I assume 90% of people who would use this would host themselves.
