### ISSUE TITLE
can use wildcards with rest api if using LIKE comparator

### ISSUE THREAD

**Issue by kenoyer130** [jundis/CWSlack-SlashCommands#34]
This was asked in #33 but that has been closed. If people are not aware wildcards can be used for most rest calls including configurations like so

example ../company/configurations?conditions=name like "PSA*"

**Comment by briangig** [comment]
This method works when searching for contacts, but not configs.  I am not sure if it is the code or an API limitation.

**Comment by kenoyer130** [comment]
This should be working for all end points. Can you post the exact rest call your making (minus the domain like above).

**Comment by jundis** [comment]
Contains works just fine in my opinion, a good example of this is below. Our CW records contains many Domain Administrator records, and a lot of other Domain [something here]. We have no records just titled Domain.

`/v4_6_release/apis/3.0/company/configurations?conditions=name%20contains%20%27Domain%27&pagesize=1`

Returns a record for "name": "Domain Administrator\Password",

`/v4_6_release/apis/3.0/company/configurations?conditions=name%20like%20%27Domain%27&pagesize=1`

Returns no records.

Now if you append a wildcard \* to the end of Domain:

`/v4_6_release/apis/3.0/company/configurations?conditions=name%20like%20%27Domain*%27&pagesize=1`

That returns the same "name": "Domain Administrator\Password",

So really wildcard isn't necessary as long as contains is used instead of like. I could add a catch for wildcards to convert the URL to using like if necessary, as Domain\* using contains will return nothing.
